### ISSUE TITLE
No package matching 'php8.1-mb' is available

### ISSUE THREAD

**Issue by elor** [tpokorra/Debian-Ansible-CiviCRM-Drupal#1]
Hi,

On a fresh Debian 11 VM, ansible fails to find the package `php8.1-mb`.
Should that be `php8.1-mbstring`, or is it actually missing?

Detailed error:

    TASK [Install Apache and PHP Packages] *******************************************************************
    fatal: [civicrm]: FAILED! => {"changed": false, "msg": "No package matching 'php8.1-mb' is available"}
    
    PLAY RECAP ***********************************************************************************************
    civicrm                    : ok=12   changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

Best regards

**Comment by tpokorra** [comment]
Thank you @elor!
You are right.
I committed this during the conference, and seems I was not concentrated...

**Comment by elor** [comment]
Don't worry 😀👍

It fails again further down the road;
I'll have to take a closer look later.

Thank you for your presentation at the conference

**Comment by tpokorra** [comment]
@elor Perhaps you have an issue with LXD, which I also had.

see https://www.drupal.org/project/drupal/issues/2945034#comment-12910956

> The workaround for the excessive composer times on LXD container on ZFS (~15 minutes) is to Disable Transparent Huge Page Support on the host before running composer in the container, like this:

```
echo never > /sys/kernel/mm/transparent_hugepage/enabled
```
